---
# Globale Einstellungen
settings:
  download_dir: /tmp  # Relativer oder absoluter Pfad zum Download-Verzeichnis
  max_redirects: 5
  timeout: 60
  check_pubDate: 1
  check_filesize: 0
  only_new_info: 0
user_agent: "PodcastDownloader/1.0"

# Liste der Podcast-Feeds
feeds:
  - name: "13 Minutes to the Moon"
    url: "https://podcasts.files.bbci.co.uk/w13xttx2.rss"
    enabled: false

  - name: "Chaosradio"
    url: "https://chaosradio.de/feed/m4a"
    enabled: true

  - name: "Das Klima"
    url: "https://dasklima.podigee.io/feed/mp3"
    enabled: true

  - name: "Datenfreiheit"
    url: "https://www.baden-wuerttemberg.datenschutz.de/rss/podcast"
    enabled: true

  - name: "Engineering Kiosk"
    url: "https://engineeringkiosk.dev/podcast/rss"
    enabled: true

  - name: "Methodisch inkorrekt"
    url: "https://minkorrekt.de/feed/m4a/"
    enabled: true

  - name: "NDR Coronavirus-Update"
    url: "https://www.ndr.de/nachrichten/info/podcast4684.xml"
    enabled: true

  - name: "omega tau"
    url: "http://omegataupodcast.net/feed/mp3/"
    enabled: true

  - name: "Request for Comments"
    url: "https://requestforcomments.de/feed/m4a"
    enabled: true

